### ISSUE TITLE
Marketing Site - Log In / Sign Up

### ISSUE THREAD

**Issue by jacobsmith928** [datumforge/datum-ui#115]
Awaiting feedback / approval.

- I've not included additional messaging about why we'd prefer you to choose 3rd party sign up, as the UI has been designed to encourage that, and we're in danger of cluttering the UI with too much info..

![Image](https://github.com/datumforge/datum-ui/assets/21034162/f436546f-4e81-4798-bf79-bf3b786a773c)

![Image](https://github.com/datumforge/datum-ui/assets/21034162/366e364c-b7b9-4ea0-8028-582dafae8a52)

![Image](https://github.com/datumforge/datum-ui/assets/21034162/69467081-f140-4011-b19d-5a3dd5179b27)

![Image](https://github.com/datumforge/datum-ui/assets/21034162/1783f1f8-2086-491d-ab60-e77a66fb6e18)

![Image](https://github.com/datumforge/datum-ui/assets/21034162/9602aeb1-0822-4699-9514-3da552e9d0d7)

![Image](https://github.com/datumforge/datum-ui/assets/21034162/b1890971-c884-4693-8544-90f12a6c7c57)

**Comment by chrisberridge** [comment]
@chrisberridge test
