### ISSUE TITLE
[Bug] Show/Hide Password doesn't work on registration

### ISSUE THREAD

**Issue by golanglemonade** [datumforge/datum-ui#126]
On Signup, the password is not revealed when the reveal button is hit: 
<img width="467" alt="image" src="https://github.com/datumforge/datum-ui/assets/147884153/b22aaeca-9f1b-4b35-a525-d22d267ac07b">

Vs. Login, it does work 
<img width="455" alt="image" src="https://github.com/datumforge/datum-ui/assets/147884153/c670d60a-6c2b-440d-80a4-75e3e51e1615">

**Comment by silaselisha** [comment]
@golanglemonade a polite request to be assigned this task

**Comment by golanglemonade** [comment]
@silaselisha Yeah, please go ahead. Let me know if you have any questions, appreciate the contributions!

**Comment by silaselisha** [comment]
@golanglemonade Hi, while reproducing the bug, I steady run to error after following the stated setup approach in the README.md

![datum](https://github.com/datumforge/datum-ui/assets/86970666/a8a5064d-1a50-4e73-911e-68bb05582f91)

**Comment by golanglemonade** [comment]
In the repo there is a `task` file (https://taskfile.dev/installation/). Have you tried running the following: 

```
task install
task build
```

Once those are successful, running the following should start up the UI, which will run on localhost:3001 by default 
```
task dev:operator
```

**Comment by silaselisha** [comment]
@golanglemonade thank you, it works now.
