### ISSUE TITLE
[Feature Request] Explain the difference between name and display name when creating workspace

### ISSUE THREAD

**Issue by mustela** [datumforge/datum-ui#212]
I think it would be useful to explain the difference between the 'name' and the 'display name.' I'm assuming the 'name' is more like a slug, and the 'display name' could even be inferred from the name, or vice versa.

GitHub shows how the 'name' is actually being used.

![Screenshot 2024-08-09 at 07 55 57](https://github.com/user-attachments/assets/46be7b47-59bc-4ad8-9282-be9e81001fc7)

**Comment by golanglemonade** [comment]
This is going to be removed and only require a single input, waiting on a backend change so closing this out.
